// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDASFJ4evj73bdK85vAEjR_AWo1X1uhbg',
    appId: '1:515157067414:web:0dc8ae7a497910cbb2e4b7',
    messagingSenderId: '515157067414',
    projectId: 'studiodentistico-1a349',
    authDomain: 'studiodentistico-1a349.firebaseapp.com',
    storageBucket: 'studiodentistico-1a349.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABZq2PCCaDWiKH1aZn-b1_dZXaNpk-CFQ',
    appId: '1:515157067414:android:8dfff6aa0c32b4e7b2e4b7',
    messagingSenderId: '515157067414',
    projectId: 'studiodentistico-1a349',
    storageBucket: 'studiodentistico-1a349.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIrokpUOP_w_wxyirlK2N76psWDlZUkkY',
    appId: '1:515157067414:ios:47ce3ccb2633812eb2e4b7',
    messagingSenderId: '515157067414',
    projectId: 'studiodentistico-1a349',
    storageBucket: 'studiodentistico-1a349.appspot.com',
    iosClientId: '515157067414-7lc32eam3j5oluk2ea7u8eodkcijecvn.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatislove',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIrokpUOP_w_wxyirlK2N76psWDlZUkkY',
    appId: '1:515157067414:ios:47ce3ccb2633812eb2e4b7',
    messagingSenderId: '515157067414',
    projectId: 'studiodentistico-1a349',
    storageBucket: 'studiodentistico-1a349.appspot.com',
    iosClientId: '515157067414-7lc32eam3j5oluk2ea7u8eodkcijecvn.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatislove',
  );
}
